name: Send Telegram Notification
on:
  issues:
    types:
      - opened
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Send a notification to the maintainer group
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_MNTR }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            New issue opened!
            *${{ github.event.issue.title }}* 
            by *${{ github.actor }}*

            • [See opened issue](https://github.com/halcyonproject/.github/issues)
      - name: Send a notification to public channel
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CH }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            New issue opened!
            *${{ github.event.issue.title }}* 
            by *${{ github.actor }}*

            • [See opened issue](https://github.com/halcyonproject/.github/issues)